[dev]
command = 'vite'
targetPort = 5173
autoLaunch = false
port = 8877

[build]
command = 'vite build'

[functions]
directory = 'server'
node_bundler = "esbuild"
external_node_modules = ["express", "telegraf"]

[[redirects]]
force = true
from = "/api/*"
status = 200
to = "/.netlify/functions/api/:splat"

[[redirects]]
force = true
from = "/bot/*"
to = "/.netlify/functions/bot/:splat"
status = 200
