export { default as ambientOcclusion } from './AmbientOcclusion.jpg'
export { default as color } from './Color.jpg'
export { default as displacement } from './Displacement.jpg'
export { default as normalGL } from './NormalGL.jpg'
export { default as roughness } from './Roughness.jpg'
